
export interface News {
    Id: string
    Title: string
    URL: string
    TimePublished: string
    Authors: string[]
    Summary: string
    BannerImage: string
    Source: string
    CategoryWithinSource: string
    SourceDomain: string
    Topics: string[]
    OverallSentimentScore: number
    OverallSentimentLabel: string
    TickerSentiment: string[]
}

export interface Company {
    Id: string
    Symbol: string
    Name: string
    Type: string
    Region: string
    MarketOpen: string
    MarketClose: string
    Timezone: string
    Currency: string
    MatchScore: number
    AssetType: string
    Description: string
    Cik: string
    Exchange: string
    Country: string
    Sector: string
    Industry: string
    Address: string
    FiscalYearEnd: string
    LatestQuarter: string
    MarketCapitalization: string
    Ebitda: string
    PERatio: string
    PEGRatio: string
    BookValue: string
    DividendPerShare: string
    DividendYield: string
    Eps: string
    RevenuePerShareTTM: string
    ProfitMargin: string
    OperatingMarginTTM: string
    ReturnOnAssetsTTM: string
    ReturnOnEquityTTM: string
    RevenueTTM: string
    GrossProfitTTM: string
    DilutedEPSTTM: string
    QuarterlyEarningsGrowthYOY: string
    QuarterlyRevenueGrowthYOY: string
    AnalystTargetPrice: string
    TrailingPE: string
    ForwardPE: string
    PriceToSalesRatioTTM: string
    PriceToBookRatio: string
    EVToRevenue: string
    EVToEBITDA: string
    Beta: string
    The52WeekHigh: string
    The52WeekLow: string
    The50DayMovingAverage: string
    The200DayMovingAverage: string
    SharesOutstanding: string
    DividendDate: string
    ExDividendDate: string
}
