
export const graphStyle: cytoscape.Stylesheet[] = [
    {
        selector: 'node[sbgnclass = "macromolecule"]',
        style: {
            label: 'data(id)',
            'font-family': 'Amazon Ember, Helvetica, Arial, sans-serif',
            'text-valign': 'bottom',
            'text-halign': 'center',
            'font-size': '5rem',
            'text-margin-y': 3,
            'background-color': '#fff',
            'background-fit': 'cover',
            'background-opacity': 1,
            'shape': 'ellipse',
            'color': '#000',
            'background-width-relative-to': 'inner',
            'background-height-relative-to': 'inner',
            'background-width': '50%',
            'background-height': '50%',
            'padding-left': '5px',
            'padding-right': '5px',
            'padding-bottom': '5px',
            'padding-top': '5px',
            'border-style': 'solid',
            'border-width': '1',
            'border-color': 'red',
        },
    },
    {
        selector: 'node[sbgnclass = "simple chemical"]',
        style: {
            label: 'data(id)',
            'font-size': '7rem',
            'font-family': 'Amazon Ember, Helvetica, Arial, sans-serif',
            'text-valign': 'top',
            'text-halign': 'center',
            'background-opacity': 0.05,
            'border-style': 'dashed',
            'border-width': 1,
            'text-background-opacity': 1,
            'text-background-shape': 'rectangle',
            'text-background-padding': '5px',
            'background-image': function (ele) { return ele.data('image') ?? 'none' },
            'text-margin-y': -4.5,
            'text-border-width': 2,
            shape: 'roundrectangle',
            color: '#fafafa',
        },
    },
    {
        selector: '.node[sbgnclass = "simple chemical"]:active',
        style: {
            'overlay-color': '#683dc2',
            'overlay-opacity': 0.45,
        },
    },
    {
        selector: 'node[sbgnclass = "simple chemical"]:selected',
        style: {
            'overlay-color': '#683dc2',
            'overlay-opacity': 0.25,
        },
    }, {
        selector: 'edge',
        style: {
            'curve-style': 'bezier',
            'target-arrow-shape': 'none',
            width: '1px',
            'line-style': 'solid',
            'line-color': '#545B64',
        },
    },
    {
        selector: 'edge.hidden',
        style: {
            width: '1px',
            'line-opacity': 0,
        },
    },
    {
        selector: 'edge.highlight',
        style: {
            'curve-style': 'bezier',
            'target-arrow-shape': 'none',
            width: '2px',
            'line-style': 'dashed',
            'line-color': '#545B64',
        },
    },
    {
        selector: 'edge.cy-expand-collapse-meta-edge',
        style: {
            'curve-style': 'unbundled-bezier',
            'control-point-distances': '0 0 0',
            'line-style': 'dashed',
            'line-color': '#ec7211',
            width: '2px',
        },
    },
]