
export const graphStyle: cytoscape.Stylesheet[] = [
    {
        selector: 'node[sbgnclass = "macromolecule"]',
        style: {
            label: 'data(id)',
            'font-family': 'Amazon Ember, Helvetica, Arial, sans-serif',
            'text-valign': 'bottom',
            'text-halign': 'center',
            'font-size': '5rem',
            'text-margin-y': 3,
            'background-color': '#fff',
            'background-fit': 'cover',
            'background-opacity': 1,
            'shape': 'ellipse',
            'color': '#000',
            'background-width-relative-to': 'inner',
            'background-height-relative-to': 'inner',
            'background-width': '50%',
            'background-height': '50%',
            'padding-left': '5px',
            'padding-right': '5px',
            'padding-bottom': '5px',
            'padding-top': '5px',
            'border-style': 'solid',
            'border-width': '1',
            'border-color': 'red',
        },
    },
    {
        selector: 'node[sbgnclass = "simple chemical"]',
        style: {
            label: 'data(id)',
            'font-size': '7rem',
            'font-family': 'Amazon Ember, Helvetica, Arial, sans-serif',
            'text-valign': 'top',
            'text-halign': 'center',
            'background-opacity': 0.05,
            'border-style': 'dashed',
            'border-width': 1,
            'text-background-opacity': 1,
            'text-background-shape': 'rectangle',
            'text-background-padding': '5px',
            'background-image': 'data(image)',
            'text-margin-y': -4.5,
            'text-border-width': 2,
            shape: 'roundrectangle',
            color: '#fafafa',
        },
    },
]